name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bundle release assets
        run: |
          RELEASE_DIR="mil-${{ github.ref_name }}"
          mkdir -p "$RELEASE_DIR"

          cp -r images-400px-webp "$RELEASE_DIR/"
          cp -r metadata "$RELEASE_DIR/"
          cp IMAGE_LICENSE.md "$RELEASE_DIR/"

          tar -czf "$RELEASE_DIR.tar.gz" "$RELEASE_DIR/"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: mil-${{ github.ref_name }}.tar.gz
          body: |
            This release includes the following assets:
            - images-400px-webp
            - metadata
            - IMAGE_LICENSE.md
            See the [ASM MIL committee page](https://www.mammalsociety.org/committees/mammal-images-library) for details on the licensing of the included images.
